- src/spaceone/inventory/manager/collector_manager/collecting_manager.py
> etc: add LOGGER for debug

- src/spaceone/inventory/manager/collector_manager/collecting_manager.py
> etc: remove LOGGER for debug

- src/spaceone/inventory/api/v1/cloud_service_tag.py
- src/spaceone/inventory/conf/proto_conf.py
- src/spaceone/inventory/info/__init__.py
- src/spaceone/inventory/info/cloud_service_info.py
- src/spaceone/inventory/info/cloud_service_tag_info.py
- src/spaceone/inventory/manager/__init__.py
- src/spaceone/inventory/manager/cloud_service_tag_manager.py
- src/spaceone/inventory/model/__init__.py
- src/spaceone/inventory/model/cloud_service_model.py
- src/spaceone/inventory/model/cloud_service_tag_model.py
- src/spaceone/inventory/service/__init__.py
- src/spaceone/inventory/service/cleanup_service.py
- src/spaceone/inventory/service/cloud_service_service.py
- src/spaceone/inventory/service/cloud_service_tag_service.py
- test/factory/cloud_service_factory.py
- test/factory/cloud_service_tag_factory.py
- test/service/test_cloud_service_tag.py
> feat: apply CloudServiceTag in CloudService

- src/spaceone/inventory/info/cloud_service_info.py
> bugfix: fix data field of cloud_service_info

- src/spaceone/inventory/service/cloud_service_service.py
- test/service/test_cloud_service_tag.py
> feat: change only requests when listing cloud service

- src/spaceone/inventory/model/cloud_service_model.py
- src/spaceone/inventory/model/cloud_service_tag_model.py
- src/spaceone/inventory/service/cloud_service_service.py
- test/service/test_cloud_service_tag.py
> refactor: change PROVIDER to MANAGED in cloud_service

- src/spaceone/inventory/info/cloud_service_tag_info.py
> bugfix: fix typo in CloudServiceTagInfo

- src/spaceone/inventory/info/cloud_service_tag_info.py
> bugfix: apply datetime_to_iso8601 function in cloud_service_tag_info

- src/spaceone/inventory/service/cloud_service_service.py
> feat: add a filter that uses cloud_service_id to change tags

- src/spaceone/inventory/api/v1/job.py
- src/spaceone/inventory/api/v1/job_task.py
- src/spaceone/inventory/manager/collector_manager/job_manager.py
- src/spaceone/inventory/manager/collector_manager/job_task_manager.py
- src/spaceone/inventory/service/job_service.py
- src/spaceone/inventory/service/job_task_service.py
A new method has been added to job, job-task.
- `Job.delete`
- `Job.get`
- `JobTask.delete`
- `JobTask.get`
- #16
> create delete and get method in job, job_task

- src/spaceone/inventory/manager/cloud_service_type_manager.py
- src/spaceone/inventory/model/cloud_service_type_model.py
- src/spaceone/inventory/model/region_model.py
- src/spaceone/inventory/service/change_history_service.py
- src/spaceone/inventory/service/cloud_service_tag_service.py
- Fix permission bug in `CloudServiceTag.list`
- Optimize index for performance
- CloudServicetype
- Region
> Refactor CloudServiceTag.list and DB Index

- src/spaceone/inventory/service/cloud_service_tag_service.py
Signed-off-by: Seolmin Kwon <seolmin@megazone.com>
> refactor: change cloud_service_id to optional field

- src/spaceone/inventory/manager/change_history_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
- remove from project_id in record queries
> Refactor Change History

- src/spaceone/inventory/model/cloud_service_model.py
> refactor: change cloud service index

- src/spaceone/inventory/model/cloud_service_model.py
- change `COMPOUND_INDEX_FOR_SEARCH_1` in cloud service
- remove `COMPOUND_INDEX_FOR_COLLECTOR` in cloud service
> Optimize Cloud Service Index

- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/model/cloud_service_model.py
- Change cloud service index
- Optimize query for AWS DocumentDB
> Optimize Performance

- src/spaceone/inventory/manager/collector_manager/collecting_manager.py
- src/spaceone/inventory/service/cleanup_service.py
> Change Debugging Code

- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/service/cleanup_service.py
- fix garbage collection bug in cleanup scheduler
> Fix GC Bug

- src/spaceone/inventory/service/cleanup_service.py
- Change query when old cloud service is deleted by cleanup scheduler
- Add only option
> Change Garbage Collection Query

- src/spaceone/inventory/model/collector_model.py
- change max length of `plugin_id` field
> Change Field Spec of Collector Model

- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
* modify get_provider method when creating and updating a CloudService
> modify get_provider method when creating and updating a CloudService

- src/spaceone/inventory/manager/change_history_manager.py
- src/spaceone/inventory/manager/cloud_service_manager.py
- change `merge_keys`
- change `diff_keys`
> Change Merge Policy When Updating Cloud Service

- src/spaceone/inventory/service/cloud_service_service.py
> Fix Bug When Updating Cloud Service

- src/spaceone/inventory/api/v1/collector_rule.py
- src/spaceone/inventory/conf/proto_conf.py
- src/spaceone/inventory/error/__init__.py
- src/spaceone/inventory/error/collector_rule.py
- src/spaceone/inventory/info/__init__.py
- src/spaceone/inventory/info/collector_rule_info.py
- src/spaceone/inventory/manager/__init__.py
- src/spaceone/inventory/manager/collector_rule_manager.py
- src/spaceone/inventory/manager/identity_manager.py
- src/spaceone/inventory/model/__init__.py
- src/spaceone/inventory/model/collector_rule_model.py
- src/spaceone/inventory/service/collector_rule_service.py
Add Collector Rule feature.
When Collector collects Cloud Service resources, it performs the function of changing resource data (ex. modifying related Project) through CollectorRules.
* https://github.com/cloudforet-io/inventory/issues/24
> Add Collector Rule feature

- src/spaceone/inventory/manager/collector_manager/__init__.py
- src/spaceone/inventory/manager/collector_manager/plugin_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
- src/spaceone/inventory/service/collector_rule_service.py
- test/factory/collector_factory.py
- test/factory/collector_rule_factory.py
- test/service/test_collector_rule_service.py
Add change cloud service data logic through collector rule.
* https://github.com/cloudforet-io/inventory/issues/24
> Add change cloud service data logic through collector rule

- src/spaceone/inventory/api/v1/collector_rule.py
- test/service/test_collector_rule_service.py
typo (CollectorRulesInfo)
* https://github.com/cloudforet-io/inventory/issues/24
> typo (CollectorRulesInfo)

- src/spaceone/inventory/manager/collector_rule_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
Modify change_cloud_service_data method.
Modify the method to get the collector_id from the metadata of the transaction.
* https://github.com/cloudforet-io/inventory/issues/24
> Modify change_cloud_service_data method

- src/spaceone/inventory/service/cloud_service_service.py
* modify change_only_tags in CloudService
> modify change_only_tags in CloudService

- src/spaceone/inventory/manager/collector_rule_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
- Improve the collector rule process when creating or updating cloud services
> Refactor Collector Rule Process

- src/spaceone/inventory/service/cloud_service_service.py
* modify change_sort_tags in CloudService
> modify change_sort_tags in CloudService

- src/spaceone/inventory/service/cloud_service_service.py
* divide convert_tags method into two methods: type checking and hash generation.
> divide convert_tags method into two methods: type checking and hash generation.

- src/spaceone/inventory/manager/cloud_service_manager.py
> fix: fix typo

- deploy/helm/templates/_helpers.tpl
- skaffold.template.yaml
Add Skaffold template file for developer
> Add Skaffold template

- .gitignore
- skaffold.template.yaml
* modify skaffold.template.yaml
* modify gitignore
> Modify skaffold.template.yaml and gitignore

- src/spaceone/inventory/conf/global_conf.py
- change default configuration
- `RESOURCE_TERMINATION_TIME` (6 Months -> 3 Months)
> feat: change resource termination time

- src/spaceone/inventory/manager/collector_rule_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
> add LOGGER for debug

- src/spaceone/inventory/manager/collector_rule_manager.py
- src/spaceone/inventory/manager/identity_manager.py
> Add cache for list projects

- src/spaceone/inventory/service/cloud_service_service.py
> Remove logger for debug

- Dockerfile
Remove --pre option in Dockerfile
> Remove --pre option in Dockerfile

- .github/workflows/CI_master_push.yml
- Dockerfile
Modify dockerfile and githubaction for dynamic pre options
> Modify dockerfile and githubaction for dynamic pre options

- .github/workflows/CI_master_push.yml
> Modify PIP_ADDITIONAL_OPTION

- .github/workflows/CI_master_push.yml
Add push true for upload docker image
> Add push true for upload docker image

- .github/workflows/CI_master_push.yml
> Modify with.tags

- .github/workflows/CI_master_push.yml
> Add login to docker hub step

- src/spaceone/inventory/manager/collector_manager/secret_manager.py
> etc: logger

- src/spaceone/inventory/info/collector_info.py
- src/spaceone/inventory/manager/collector_manager/__init__.py
- src/spaceone/inventory/model/collector_model.py
- src/spaceone/inventory/service/collector_service.py
Integrate collector schedule into Collector. 
schedule APIs will be deprecated.
> Add schedule in Collector

- src/spaceone/inventory/model/collector_model.py
> Modify provider in Collector

- src/spaceone/inventory/info/collector_info.py
Modify provider in collector info
> Modify provider in collector info

- src/spaceone/inventory/model/collector_model.py
fix: add fields in plugin info model
> fix: add fields in plugin info model

- src/spaceone/inventory/model/collector_model.py
> Add fields in Collector model

- src/spaceone/inventory/info/collector_info.py
- fix message bug of COllectorInfo
> fix: fix message bug of CollectorInfo

- src/spaceone/inventory/manager/__init__.py
- src/spaceone/inventory/service/collector_service.py
> Import manager

- src/spaceone/inventory/model/collector_model.py
- src/spaceone/inventory/service/collector_service.py
- test/factory/collector_factory.py
- test/service/test_collector_service.py
> fix typo and schedule model

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/collector_plugin_manager.py
- src/spaceone/inventory/service/collector_service.py
Modify plugin init/verify parameter
> Modify plugin init/verify parameter

- src/spaceone/inventory/manager/secret_manager.py
> Add token for SpaceConnector

- src/spaceone/inventory/manager/secret_manager.py
- src/spaceone/inventory/service/collector_service.py
Add domain_id for list secrets
> Add domain_id for list secrets

- src/spaceone/inventory/manager/collecting_manager.py
> fix: add logger for debug

- src/spaceone/inventory/manager/collecting_manager.py
fix: modify return data type from plugin
> Modify return data type from plugin

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/collector_plugin_manager.py
- src/spaceone/inventory/manager/job_manager.py
- src/spaceone/inventory/manager/job_task_manager.py
- src/spaceone/inventory/service/collector_service.py
> Collecting logic

- src/spaceone/inventory/conf/collector_conf.py
- src/spaceone/inventory/lib/job_state.py
- src/spaceone/inventory/lib/scheduler.py
- src/spaceone/inventory/manager/cleanup_manager.py
- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/collection_state_manager.py
- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/manager/collector_plugin_manager.py
- src/spaceone/inventory/manager/collector_rule_manager.py
- src/spaceone/inventory/manager/filter_manager.py
- src/spaceone/inventory/manager/job_manager.py
- src/spaceone/inventory/manager/job_task_manager.py
- src/spaceone/inventory/scheduler/cleanup_scheduler.py
- src/spaceone/inventory/scheduler/interval_scheduler.py
- src/spaceone/inventory/scheduler/inventory_db_updater.py
- src/spaceone/inventory/scheduler/inventory_scheduler.py
- src/spaceone/inventory/service/cleanup_service.py
- src/spaceone/inventory/service/collector_service.py
- src/spaceone/inventory/service/resource_group_service.py
> Refactoring collecting logic

- src/spaceone/inventory/manager/collecting_manager.py
> fix: add total_count

- src/spaceone/inventory/manager/collecting_manager.py
> Modify options

- src/spaceone/inventory/model/collector_model.py
- src/spaceone/inventory/service/collector_service.py
Add provider filter for secret search
> Add provider filter for secret search

- src/spaceone/inventory/error/cloud_service_query_set.py
- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
> fix: fix select bug

- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- apply cascade delete when deleting a cloud service query set
> Refactor Cloud Service Query Set

- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- test/service/test_cloud_service_query_set.py
- fix test code(`test_create_cloud_service_query_set`) bug
> fix: fix test code bug

- src/spaceone/inventory/api/v1/collector.py
- src/spaceone/inventory/info/collector_info.py
- src/spaceone/inventory/model/collector_model.py
- src/spaceone/inventory/service/collector_service.py
> Update collector info

- src/spaceone/inventory/service/collector_service.py
Modify secret_filter condition
> Modify secret_filter condition

- src/spaceone/inventory/info/collector_info.py
Remove secret_filter in PluginInfo
> Remove secret_filter in PluginInfo

- src/spaceone/inventory/manager/collector_manager.py
> Modify is_supported_schedule

- src/spaceone/inventory/manager/collector_manager.py
> fix: modify is_supported_schedule

- src/spaceone/inventory/manager/repository_manager.py
- src/spaceone/inventory/service/collector_service.py
> Add validate secret_filter

- src/spaceone/inventory/service/collector_service.py
> Modify set secret filter

- src/spaceone/inventory/manager/collecting_manager.py
> Remove not use logic

- src/spaceone/inventory/lib/job_task_state.py
- src/spaceone/inventory/manager/job_task_manager.py
> Move job state machine in lib

- src/spaceone/inventory/api/v1/collector.py
- src/spaceone/inventory/info/collector_info.py
Remove related schedule (deprecated)
> Remove related schedule (deprecated)

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
- src/spaceone/inventory/service/cloud_service_type_service.py
- src/spaceone/inventory/service/region_service.py
> Modify method_name

- deploy/helm/Chart.yaml
- deploy/helm/values.yaml
- src/spaceone/inventory/interface/task/v1/interval_scheduler.py
- src/spaceone/inventory/service/collector_service.py
Modify filter_query for hourly schedule
> Modify filter_query for hourly schedule

- deploy/helm/Chart.yaml
- deploy/helm/values.yaml
> Modify Scheduler time

- src/spaceone/inventory/interface/task/v1/inventory_db_updater.py
- src/spaceone/inventory/service/collector_service.py
> modify schedule param update

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/service/collector_service.py
Remove validation schedule check
> Remove validation schedule check

- src/spaceone/inventory/service/collector_service.py
> refactor: task

- src/spaceone/inventory/model/cloud_service_query_set_model.py
> fix: fix index bug

- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- src/spaceone/inventory/manager/cloud_service_type_manager.py
- src/spaceone/inventory/model/cloud_service_query_set_model.py
> refactor: refactor managed query set

- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- src/spaceone/inventory/manager/cloud_service_type_manager.py
> fix: fix query set bug

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/service/collector_service.py
> Remove logger

- src/spaceone/inventory/model/cloud_service_model.py
> refactor: add cloud service index

- src/spaceone/inventory/model/collector_model.py
> Remove db model

- src/spaceone/inventory/interface/task/v1/cleanup_scheduler.py
- src/spaceone/inventory/manager/change_history_manager.py
- src/spaceone/inventory/manager/collection_state_manager.py
> chore: remove debug code

- src/spaceone/inventory/manager/job_task_manager.py
> Add debug error info

- src/spaceone/inventory/info/collector_info.py
- src/spaceone/inventory/info/job_info.py
- src/spaceone/inventory/lib/job_state.py
- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/job_manager.py
- src/spaceone/inventory/model/collector_model.py
- src/spaceone/inventory/model/job_model.py
- src/spaceone/inventory/service/collector_service.py
- src/spaceone/inventory/service/job_service.py
> Improve collector, job

- src/spaceone/inventory/info/job_info.py
- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/model/job_model.py
- src/spaceone/inventory/service/collector_service.py
> fix: add collector_id in info

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/model/job_model.py
- src/spaceone/inventory/service/collector_service.py
fix: add updatable_fields projects in Job
> fix: add updatable_fields projects in Job

- src/spaceone/inventory/manager/collecting_manager.py
fix: update failure task count
> update failure task count

- src/spaceone/inventory/service/collector_service.py
> add plugin_id in job

- src/spaceone/inventory/manager/job_manager.py
Modify check condition for remained_task
> Modify check condition for remained_task

- src/spaceone/inventory/manager/collector_plugin_manager.py
- src/spaceone/inventory/service/collector_service.py
> chore: typo

- src/spaceone/inventory/service/collector_service.py
> modify task_options

- src/spaceone/inventory/service/collector_service.py
> chore: add debug

- src/spaceone/inventory/service/collector_service.py
> fix: modify get_tasks

- src/spaceone/inventory/manager/collecting_manager.py
fix: modify task status for canceled
> Modify task status for canceled

- src/spaceone/inventory/info/cloud_service_info.py
- src/spaceone/inventory/interface/grpc/v1/cloud_service.py
- src/spaceone/inventory/service/cloud_service_service.py
- apply maximum page to `CloudService.list` API (up to 1000)
> refactor: apply maximum page to CloudService.list API

- src/spaceone/inventory/conf/global_conf.py
- src/spaceone/inventory/info/cloud_service_query_set_info.py
- src/spaceone/inventory/info/cloud_service_stats_info.py
- src/spaceone/inventory/interface/grpc/v1/cloud_service_query_set.py
- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- src/spaceone/inventory/manager/cloud_service_stats_manager.py
- src/spaceone/inventory/manager/cloud_service_type_manager.py
- src/spaceone/inventory/model/cloud_service_query_set_model.py
- src/spaceone/inventory/model/cloud_service_stats_model.py
- src/spaceone/inventory/service/cloud_service_query_set_service.py
- src/spaceone/inventory/service/cloud_service_service.py
- src/spaceone/inventory/service/cloud_service_stats_service.py
- refactor CloudServiceQuerySet
- refactor CloudServiceStats
- remove `resource_group_id` filter in CloudService.list API
> Refactor Cloud Service Query Set and Stats

- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- src/spaceone/inventory/manager/cloud_service_stats_manager.py
> fix: fix cache bug

- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- fix query bug in CloudServiceQuerySet
> fix: fix query bug in CloudServiceQuerySet

- pkg/pip_requirements.txt
- src/setup.py
> build: add openpyxl package

- src/spaceone/inventory/info/cloud_service_query_set_info.py
- src/spaceone/inventory/info/cloud_service_report_info.py
- refactor message creation using `ParseDict`
> refactor: refactor message creation

- src/spaceone/inventory/manager/cloud_service_manager.py
- fix bug when converting array
> fix: fix bug when converting array

- src/spaceone/inventory/plugin/collector/error/response.py
- src/spaceone/inventory/plugin/collector/interface/grpc/collector.py
- src/spaceone/inventory/plugin/collector/model/cloud_service.py
- src/spaceone/inventory/plugin/collector/model/cloud_service_type.py
- src/spaceone/inventory/plugin/collector/model/collector_response.py
- src/spaceone/inventory/plugin/collector/model/region.py
- src/spaceone/inventory/plugin/collector/service/collector_service.py
- src/spaceone/inventory/plugin/collector/skeleton/main.py
* Remove unnecessary imports
* Union type added to service return
* Refine the fields of ResourceResponse
* Add resource pydantic model
> fix: add schema of resources in collector template

- src/spaceone/inventory/plugin/collector/error/response.py
- src/spaceone/inventory/plugin/collector/interface/grpc/collector.py
* Add validation of resource and resource_type in Collector api of plugin
> feat: add validation of resource and resource_type in Collector api of plugin

- src/spaceone/inventory/plugin/collector/error/response.py
- src/spaceone/inventory/plugin/collector/interface/grpc/collector.py
- src/spaceone/inventory/plugin/collector/lib/__init__.py
- src/spaceone/inventory/plugin/collector/lib/metadata.py
- src/spaceone/inventory/plugin/collector/lib/server.py
- src/spaceone/inventory/plugin/collector/lib/utils.py
- src/spaceone/inventory/plugin/collector/model/__init__.py
- src/spaceone/inventory/plugin/collector/model/cloud_service.py
- src/spaceone/inventory/plugin/collector/skeleton/main.py
* Add helper function for plugin developer
- make_cloud_service_type
- make_cloud_service
- make_response
- make_error_response
> feat: add helper function for plugin developer

- src/spaceone/inventory/plugin/collector/lib/metadata.py
- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/model/dynamic_view.py
- src/spaceone/inventory/plugin/collector/model/field.py
* Add search and table generator for converting metadata
* Tabs generator not implemented yet
> feat: add generator for converting metadata

- src/spaceone/inventory/plugin/collector/lib/metadata.py
> chore: add debug code

- src/spaceone/inventory/plugin/collector/lib/metadata.py
* Modify app_path to find yaml file
> fix: modify app_path to find yaml file

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
* Change string layout to layouts in metadata_generator
> fix: change string layout to layouts in metadata_generator

- pkg/pip_requirements.txt
- src/setup.py
- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/manager/cloud_service_report_manager.py
- src/spaceone/inventory/service/cloud_service_report_service.py
- src/spaceone/inventory/service/cloud_service_service.py
- fix type bug when exporting cloud service
- add `timezone` option to cloud service export API
- add `timezone` and `language` options to cloud service APIs
> Refactor Cloud Service Export API

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/model/field.py
* Add 10 types of field generators and models in MetadataGenerator
* TextField
* DictField
* SizeField
* ProgressField
* DatetimeField
* StateField
* BadgeField
* ImageField
* MoreField
* EnumField
> add 10 types of field generators and models in MetadataGenerator

- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/manager/export_manager/__init__.py
- src/spaceone/inventory/service/cloud_service_service.py
- fix float type bug
- fix null type bug in array
- change duplicate sheet name
- add `file_name` option
> Fix Bugs in Cloud Service Export API

- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/manager/export_manager/__init__.py
- add style to excel
- remove empty value in excel
- implement title option in excel
> Apply Excel Style and Title Option

- src/spaceone/inventory/manager/export_manager/__init__.py
- exclude empty result in excel
> refactor: exclude empty result in excel

- src/spaceone/inventory/info/cloud_service_report_info.py
- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/manager/cloud_service_report_manager.py
- src/spaceone/inventory/model/cloud_service_report_model.py
- src/spaceone/inventory/service/cloud_service_report_service.py
- add language and timezone options to CloudServiceReport API
- apply field options in CloudService.export API
> Improve Cloud Service Export API

- src/spaceone/inventory/info/cloud_service_query_set_info.py
- src/spaceone/inventory/info/cloud_service_report_info.py
- src/spaceone/inventory/info/cloud_service_stats_info.py
- src/spaceone/inventory/interface/grpc/cloud_service_query_set.py
- src/spaceone/inventory/interface/grpc/cloud_service_report.py
> fix: fix grpc message bug

- src/spaceone/inventory/manager/export_manager/__init__.py
- improve performance of cloud service export API
> refactor: improve performance of cloud service export API

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
* Add root_path field in dynamic views
> fix: add root_path field in dynamic views

- src/spaceone/inventory/error/__init__.py
- src/spaceone/inventory/error/export.py
- src/spaceone/inventory/manager/export_manager/__init__.py
- change excel style for performance
> refactor: change excel style

- src/spaceone/inventory/info/cloud_service_query_set_info.py
- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- src/spaceone/inventory/model/cloud_service_query_set_model.py
* Accoding to change spec ichange data_keys to keys in cloud_service_query_set
> fix: change data_keys to keys in cloud_service_query_set

- src/spaceone/inventory/info/cloud_service_query_set_info.py
- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- src/spaceone/inventory/model/cloud_service_query_set_model.py
* change keys to data_keys in cloud_service_query_set
> fix: change keys to data_keys in cloud_service_query_set

- src/spaceone/inventory/plugin/collector/lib/metadata.py
- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
> fix: fix get_yaml_path method

- deploy/helm/Chart.yaml
- deploy/helm/values.yaml
- change scheduler config in helm chart
> build: change scheduler config in helm chart

- src/spaceone/inventory/manager/identity_manager.py
- src/spaceone/inventory/manager/secret_manager.py
- src/spaceone/inventory/model/collector_model.py
- src/spaceone/inventory/service/collector_service.py
> refactor: refactor collector

- src/spaceone/inventory/manager/collector_plugin_manager.py
- src/spaceone/inventory/service/collector_service.py
- fix communication issue with plugin
> fix: fix communication issue with plugin

- src/spaceone/inventory/lib/resource_manager.py
- src/spaceone/inventory/lib/rule_matcher.py
- src/spaceone/inventory/manager/collecting_manager.py
> refactor: refactor collecting process

- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/manager/cloud_service_type_manager.py
- src/spaceone/inventory/manager/collector_rule_manager.py
- src/spaceone/inventory/service/collector_rule_service.py
> fix: fix collecting issue

- src/spaceone/inventory/model/collector_model.py
- src/spaceone/inventory/model/job_model.py
- src/spaceone/inventory/service/collector_service.py
- change spec of job model
- change schedule policy in collector
- add total_tasks value to job info
> Refactor Collector

- src/spaceone/inventory/service/collector_service.py
…collect
- Add defensive code dict type when get secret filter at Collect.collect
> Add defensive code dict type when get secret filter at Collect.collect

- src/spaceone/inventory/info/note_info.py
- src/spaceone/inventory/manager/job_task_manager.py
- src/spaceone/inventory/service/collector_rule_service.py
- src/spaceone/inventory/service/note_service.py
> Change All for SpaceONE 2.0

- deploy/helm/values.yaml
- src/spaceone/inventory/service/collector_service.py
- change authorization policy in Collector.collect API
- change worker thread pool
> Change authorization policy in Collector.collect API

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/job_task_manager.py
- src/spaceone/inventory/model/job_task_model.py
- src/spaceone/inventory/service/collector_service.py
- refactor creation logic of job task
> refactor: refactor creation logic of job task

- src/spaceone/inventory/plugin/collector/service/collector_service.py
- src/spaceone/inventory/plugin/collector/service/job_service.py
> fix: change transaction variables for asset plugin

- src/spaceone/inventory/interface/task/v1/cleanup_scheduler.py
- src/spaceone/inventory/interface/task/v1/inventory_scheduler.py
- src/spaceone/inventory/service/__init__.py
> fix: fix schedule bugs

- src/spaceone/inventory/model/cloud_service_query_set_model.py
- src/spaceone/inventory/model/cloud_service_type_model.py
- src/spaceone/inventory/model/region_model.py
> refactor: change indexes

- src/spaceone/inventory/manager/collector_plugin_manager.py
- src/spaceone/inventory/manager/file_manager.py
- src/spaceone/inventory/manager/identity_manager.py
- src/spaceone/inventory/manager/secret_manager.py
> refactor: refactor SpaceConnector

- src/spaceone/inventory/manager/collector_plugin_manager.py
* add no_token in collector plugin manager
> fix: add no_token in collector plugin manager

- src/spaceone/inventory/manager/cleanup_manager.py
- src/spaceone/inventory/manager/identity_manager.py
- src/spaceone/inventory/manager/plugin_manager.py
- src/spaceone/inventory/manager/secret_manager.py
- src/spaceone/inventory/service/cleanup_service.py
- apply internal authentication
> feat: apply internal authentication

- src/spaceone/inventory/model/region_model.py
- src/spaceone/inventory/service/region_service.py
> refactor: add ref_region field

- src/spaceone/inventory/manager/identity_manager.py
- src/spaceone/inventory/manager/plugin_manager.py
- src/spaceone/inventory/manager/secret_manager.py
> fix: change wrong system token

- src/spaceone/inventory/interface/task/v1/cleanup_scheduler.py
- src/spaceone/inventory/interface/task/v1/inventory_scheduler.py
- src/spaceone/inventory/manager/identity_manager.py
> fix: fix schedule time bugs

- src/spaceone/inventory/manager/job_manager.py
> fix: fix wrong filter

- src/spaceone/inventory/service/collector_service.py
- fix update_plugin parameter order
> Fix update_plugin parameter order

- src/spaceone/inventory/error/__init__.py
- src/spaceone/inventory/error/cloud_service.py
- src/spaceone/inventory/error/server.py
- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- src/spaceone/inventory/manager/identity_manager.py
- src/spaceone/inventory/manager/reference_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
> feat: add project_group_id filter

- src/spaceone/inventory/interface/grpc/cloud_service_query_set.py
- src/spaceone/inventory/interface/grpc/cloud_service_report.py
- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- fix bugs in CloudServiceQuerySet
> fix: fix bugs in CloudServiceQuerySet

- src/spaceone/inventory/error/cloud_service.py
- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/manager/identity_manager.py
- fix `project_group_id` filter bug
> fix: fix project_group_id filter bug

- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/manager/cloud_service_query_set_manager.py
- src/spaceone/inventory/manager/identity_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
- fix incorrect token type issue
> fix: fix incorrect token type issue

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/job_task_manager.py
- send token when executing `collecting_resources` method
> refactor: send token when executing collecting_resources method

- src/spaceone/inventory/manager/job_task_manager.py
> fix empty metadata issue

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
* add query_sets variable in metadata when creating cloud_service_type
> Add query_sets variable in metadata when creating cloud_service_type

- src/spaceone/inventory/manager/export_manager/__init__.py
- add resource_group for WORKSPACE_MEMBER for file.add api
> Add resource_group for WORKSPACE_MEMBER for file.add api

- src/spaceone/inventory/plugin/collector/model/cloud_service.py
* Change variables in CloudService pydantic model
> fix: change variables in CloudService pydantic model

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
Add is_optional and root_path variables in options
> Add is_optional and root_path variables in options

- src/spaceone/inventory/plugin/collector/model/field.py
* Add is_optional field in pydantic models
> Add is_optional field in pydantic models

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
* Change generate single dynamic view logic
> Change generate single dynamic view logic

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
* Add widget meta in metadata generator
> Add widget meta in metadata generator

- src/spaceone/inventory/plugin/collector/service/collector_service.py
- src/spaceone/inventory/plugin/collector/service/job_service.py
* Add resource for plugin debug
> Add resource for plugin debug

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
* Improve popup_key in more field for collector
> Improve popup_key in more field for collector

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
> Refactor more field

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
* Add popup type in more field
> Add popup type in more field

- src/spaceone/inventory/plugin/collector/model/collector_request.py
- src/spaceone/inventory/service/collector_service.py
> Fixed code to make collecting work when triggered by job task

- src/spaceone/inventory/service/collector_service.py
> Resolved paramter missing error by adding domain_id param

- src/spaceone/inventory/plugin/collector/model/collector_request.py
- src/spaceone/inventory/plugin/collector/service/collector_service.py
> Changed task_options to optional field when running collector plugins

- src/setup.py
- src/spaceone/inventory/error/metric.py
- src/spaceone/inventory/interface/grpc/__init__.py
- src/spaceone/inventory/interface/grpc/metric.py
- src/spaceone/inventory/interface/grpc/metric_data.py
- src/spaceone/inventory/interface/grpc/namespace.py
- src/spaceone/inventory/managed_resource/metric/created_count.yaml
- src/spaceone/inventory/managed_resource/metric/database_count.yaml
- src/spaceone/inventory/managed_resource/metric/deleted_count.yaml
- src/spaceone/inventory/managed_resource/metric/server_count.yaml
- src/spaceone/inventory/managed_resource/metric/storage_size.yaml
- src/spaceone/inventory/managed_resource/namespace/asset_summary.yaml
- src/spaceone/inventory/managed_resource/namespace/job_history.yaml
- src/spaceone/inventory/manager/managed_resource_manager.py
- src/spaceone/inventory/manager/metric_data_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/manager/namespace_manager.py
- src/spaceone/inventory/model/__init__.py
- src/spaceone/inventory/model/metric/database.py
- src/spaceone/inventory/model/metric/request.py
- src/spaceone/inventory/model/metric/response.py
- src/spaceone/inventory/model/metric_data/database.py
- src/spaceone/inventory/model/metric_data/request.py
- src/spaceone/inventory/model/metric_data/response.py
- src/spaceone/inventory/model/namespace/database.py
- src/spaceone/inventory/model/namespace/request.py
- src/spaceone/inventory/model/namespace/response.py
- src/spaceone/inventory/service/metric_data_service.py
- src/spaceone/inventory/service/metric_service.py
- src/spaceone/inventory/service/namespace_service.py
- add `Namespace` APIs
- add `Metric` APIs
- add `MetricData` APIs
> Implement Metric APIs

- src/spaceone/inventory/plugin/collector/interface/grpc/collector.py
- src/spaceone/inventory/plugin/collector/lib/utils.py
- src/spaceone/inventory/plugin/collector/model/collector_response.py
* Refactor error method logic in collector plugin
> Refactor error method logic in collector plugin

- src/spaceone/inventory/manager/job_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/metric/request.py
- src/spaceone/inventory/service/metric_data_service.py
- src/spaceone/inventory/service/metric_service.py
- append real-time data to metric data when querying
- add `query_options` to Metric.test API
> feat: append real-time data to metric data when querying

- src/spaceone/inventory/plugin/collector/lib/utils.py
* Remove traceback when error occurs in collector plugin
> Remove traceback when error occurs in collector plugin

- src/spaceone/inventory/conf/global_conf.py
- src/spaceone/inventory/managed_resource/metric/created_count.yaml
- src/spaceone/inventory/managed_resource/metric/deleted_count.yaml
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/metric/database.py
- src/spaceone/inventory/model/metric/request.py
- src/spaceone/inventory/model/metric/response.py
- src/spaceone/inventory/service/metric_service.py
- refactor logic of counter metric
> refactor: refactor logic of counter metric

- src/spaceone/inventory/managed_resource/metric/storage_size.yaml
- src/spaceone/inventory/model/metric/request.py
- fix wrong request model of MetricCreateRequest
> fix: fix wrong request model of MetricCreateRequest

- src/spaceone/inventory/error/metric.py
- src/spaceone/inventory/manager/metric_manager.py
- fix a bug when creating metric resource
> fix: fix a bug when creating metric resource

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
* Added reference, default, and field description options to text field
> Added reference, default, and field description options to text field

- deploy/helm/Chart.yaml
- deploy/helm/values.yaml
- src/spaceone/inventory/interface/grpc/__init__.py
- src/spaceone/inventory/interface/grpc/metric_example.py
- src/spaceone/inventory/interface/task/v1/metric_scheduler.py
- src/spaceone/inventory/managed_resource/metric/created_count.yaml
- src/spaceone/inventory/managed_resource/metric/database_count.yaml
- src/spaceone/inventory/managed_resource/metric/deleted_count.yaml
- src/spaceone/inventory/managed_resource/metric/server_count.yaml
- src/spaceone/inventory/managed_resource/metric/storage_size.yaml
- src/spaceone/inventory/managed_resource/namespace/asset_change_history.yaml
- src/spaceone/inventory/manager/metric_example_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/__init__.py
- src/spaceone/inventory/model/metric/request.py
- src/spaceone/inventory/model/metric_example/database.py
- src/spaceone/inventory/model/metric_example/request.py
- src/spaceone/inventory/model/metric_example/response.py
- src/spaceone/inventory/model/namespace/database.py
- src/spaceone/inventory/model/namespace/request.py
- src/spaceone/inventory/model/namespace/response.py
- src/spaceone/inventory/service/metric_example_service.py
- src/spaceone/inventory/service/metric_service.py
- src/spaceone/inventory/service/namespace_service.py
- change managed resource (namespace, metric)
- add metric scheduler
- add MetricExample APIs
> Improvement Metric Features

- src/spaceone/inventory/model/metric_example/request.py
- fix wrong type in MetricExample
> fix: fix wrong type

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/service/collector_service.py
> Slight change made for testing search metadata

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/model/field.py
> Changed search enum field metadata for testing

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
> Reverted previous commit change related to search to prevent error

- deploy/helm/Chart.yaml
- src/spaceone/inventory/interface/task/v1/metric_scheduler.py
- src/spaceone/inventory/managed_resource/metric/created_count.yaml
- src/spaceone/inventory/managed_resource/metric/database_count.yaml
- src/spaceone/inventory/managed_resource/metric/deleted_count.yaml
- src/spaceone/inventory/managed_resource/metric/server_count.yaml
- src/spaceone/inventory/managed_resource/metric/storage_size.yaml
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/metric/database.py
- src/spaceone/inventory/model/metric/response.py
- src/spaceone/inventory/service/__init__.py
- src/spaceone/inventory/service/metric_service.py
- refactor counter metric
- fix metric scheduler bug
- refactor resource_type in Metric
- refactor group_by option and label_keys
> Refactor Metric Logic

- src/spaceone/inventory/manager/metric_manager.py
- add workspaces filter when analyzing resource
> refactor: add workspaces filter when analyzing resource

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/model/field.py
> Made different changes to search field

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/model/field.py
> fix: fixed fields for reference type and data type

- src/spaceone/inventory/managed_resource/metric/created_count.yaml
- src/spaceone/inventory/managed_resource/metric/database_count.yaml
- src/spaceone/inventory/managed_resource/metric/deleted_count.yaml
- src/spaceone/inventory/managed_resource/metric/server_count.yaml
- src/spaceone/inventory/managed_resource/metric/storage_size.yaml
> feat: change managed metrics

- src/spaceone/inventory/plugin/collector/interface/grpc/collector.py
- src/spaceone/inventory/plugin/collector/lib/utils.py
- src/spaceone/inventory/plugin/collector/model/collector_response.py
- src/spaceone/inventory/plugin/collector/model/metric.py
- src/spaceone/inventory/plugin/collector/model/namespace.py
* Add Namespace and Metric spec in Response schema of collector plugin
> Add Namespace and Metric spec in Response schema of collector plugin

- src/spaceone/inventory/manager/__init__.py
- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/job_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/metric/database.py
- src/spaceone/inventory/model/namespace/database.py
- upsert feature of metric and namespace from collector
> feat: upsert feature of metric and namespace from collector

- src/spaceone/inventory/service/collector_service.py
- refactor job task creation logic
> refactor: refactor job_task creation logic

- src/spaceone/inventory/service/collector_service.py
> refactor: rollback job progress

- src/spaceone/inventory/manager/collecting_manager.py
> fix: fix collecting error

- src/spaceone/inventory/manager/collecting_manager.py
> fix: fix collecting bug

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- refactor default label keys
- fix wrong namespace and metric field
> Refactor Metric Fields

- src/spaceone/inventory/managed_resource/metric/analytics_service.yaml
- src/spaceone/inventory/managed_resource/metric/computing_service.yaml
- src/spaceone/inventory/managed_resource/metric/container_service.yaml
- src/spaceone/inventory/managed_resource/metric/database_service.yaml
- src/spaceone/inventory/managed_resource/metric/deleted_count.yaml
- src/spaceone/inventory/managed_resource/metric/networking_service.yaml
- src/spaceone/inventory/managed_resource/metric/security_service.yaml
- src/spaceone/inventory/managed_resource/metric/server_service.yaml
- src/spaceone/inventory/managed_resource/metric/storage_service.yaml
- src/spaceone/inventory/managed_resource/namespace/job_history.yaml
- change and add managed metrics
> feat: change and add managed metrics

- src/spaceone/inventory/managed_resource/metric/total_count.yaml
- add managed metric yaml for total resource count
> Add managed metric yaml for total resource count

- src/spaceone/inventory/manager/metric_data_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/metric/database.py
- src/spaceone/inventory/model/metric/response.py
- change field name (`label_keys` -> `labels_info`)
- implement deletion of metric data when metric query changes
> Improve Metric APIs

- src/spaceone/inventory/manager/cloud_service_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
- refactor cloud service query for performance
> Refactor Cloud Service Query for Performance

- src/spaceone/inventory/info/cloud_service_info.py
- src/spaceone/inventory/model/cloud_service_model.py
- src/spaceone/inventory/service/cloud_service_service.py
- src/spaceone/inventory/service/collector_service.py
- change collection_info fields in cloud service model
- change policy of collector schedule
> Change Collector and Cloud Service Model

- src/spaceone/inventory/info/cloud_service_info.py
- src/spaceone/inventory/model/metric/database.py
- change max length of metric_id in metric model
- fix info bug
> Refactor Metric Model and Fix bugs

- src/spaceone/inventory/managed_resource/metric/created_count.yaml
- src/spaceone/inventory/managed_resource/metric/deleted_count.yaml
- src/spaceone/inventory/manager/metric_manager.py
> feat: change default metrics

- src/spaceone/inventory/manager/metric_manager.py
> fix: fix wrong default metric

- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/service/metric_service.py
- fix metric bug
- change cache policy
> Fix Bugs and Refactor Cache Policy

- src/spaceone/inventory/manager/metric_data_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/__init__.py
- src/spaceone/inventory/model/metric/database.py
- src/spaceone/inventory/model/metric_data/database.py
- src/spaceone/inventory/service/metric_service.py
- remove metric query history feature
- fix duplicate analyze query bug
> Refactor Metric Features

- src/spaceone/inventory/manager/metric_manager.py
- refactor metric loading process
> refactor: refactor metric loading process

- src/spaceone/inventory/service/collector_service.py
- fix bug when collecting resource
> fix: fix bug when collecting resource

- src/spaceone/inventory/manager/collecting_manager.py
> refactor: refactor collecting manager

- src/spaceone/inventory/manager/job_task_manager.py
- src/spaceone/inventory/service/collector_service.py
- fix incorrect sub tasks
- refactor collecting process
> Fix Bugs and Refactor Collector

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/job_task_manager.py
> Fix Collector Bug

- src/spaceone/inventory/manager/collecting_manager.py
> fix: fix collector bug

- src/spaceone/inventory/manager/job_manager.py
> fix: fix job status bug

- src/spaceone/inventory/model/metric_data/database.py
- change max length of `metric_id`
> fix: change max length of metric_id

- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/metric_data/database.py
- src/spaceone/inventory/model/metric_data/response.py
> feat: change metric data field

- src/spaceone/inventory/manager/job_manager.py
- src/spaceone/inventory/manager/metric_manager.py
> Change Debug Message

- src/spaceone/inventory/manager/job_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/service/metric_data_service.py
> refactor: refactor metric process

- src/spaceone/inventory/service/cloud_service_service.py
- add json_data for performance
> refactor: add json_data for performance

- src/spaceone/inventory/service/cloud_service_service.py
> fix: fix type bug

- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/service/cloud_service_service.py
> Refactor Collecting Process

- src/spaceone/inventory/service/cloud_service_service.py
- add json_metadata for performance
> refactor: add json_metadata for performance

- src/spaceone/inventory/model/metric/database.py
> fix: fix metric bug

- src/spaceone/inventory/manager/metric_manager.py
> fix: fix wrong flag

- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/metric_data/database.py
- src/spaceone/inventory/service/metric_data_service.py
- src/spaceone/inventory/service/metric_service.py
> Refactor Metric Process

- src/spaceone/inventory/manager/metric_data_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/model/metric/database.py
- src/spaceone/inventory/model/metric_data/database.py
- refactor duplicate metric job
- change indexes
> Refactor Metric

- src/spaceone/inventory/manager/job_manager.py
- src/spaceone/inventory/model/namespace/database.py
> fix: add resource_group field

- src/spaceone/inventory/service/metric_example_service.py
> fix: fix permission bug

- src/spaceone/inventory/manager/metric_example_manager.py
- src/spaceone/inventory/model/metric_example/database.py
- src/spaceone/inventory/model/metric_example/request.py
- src/spaceone/inventory/model/metric_example/response.py
- src/spaceone/inventory/service/metric_example_service.py
- remove workspace_id field from metric example
> feat: remove workspace_id field from metric example

- src/spaceone/inventory/managed_resource/namespace/asset_change_history.yaml
- src/spaceone/inventory/managed_resource/namespace/asset_summary.yaml
- src/spaceone/inventory/manager/collecting_manager.py
- src/spaceone/inventory/manager/namespace_manager.py
- src/spaceone/inventory/model/metric/request.py
- src/spaceone/inventory/model/namespace/database.py
- src/spaceone/inventory/model/namespace/request.py
- src/spaceone/inventory/model/namespace/response.py
- src/spaceone/inventory/service/metric_service.py
- src/spaceone/inventory/service/namespace_service.py
- change namespace fields
- change metric options
> Refactor Namespace

- src/spaceone/inventory/service/metric_service.py
- change permission of Metric.run API
> refactor: change permission of Metric.run API

- src/spaceone/inventory/model/namespace/database.py
> refactor: update policy of namespace

- src/spaceone/inventory/service/metric_service.py
- fix bug when searching namespace
> fix: fix bug when searching namespace

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/model/field.py
-  add list field type at metadata generator
> Add list field type at metadata generator

- src/spaceone/inventory/plugin/collector/interface/grpc/collector.py
- src/spaceone/inventory/plugin/collector/lib/utils.py
- src/spaceone/inventory/plugin/collector/model/cloud_service.py
- src/spaceone/inventory/plugin/collector/model/cloud_service_type.py
- src/spaceone/inventory/plugin/collector/service/collector_service.py
- src/spaceone/inventory/service/cloud_service_type_service.py
> refactor: refactor plugin framework

- src/spaceone/inventory/plugin/collector/interface/grpc/collector.py
> fix: fix wrong plugin response

- src/spaceone/inventory/plugin/collector/lib/utils.py
- src/spaceone/inventory/plugin/collector/model/cloud_service_type.py
> refactor: refactor plugin model

- src/spaceone/inventory/plugin/collector/lib/utils.py
- add option for response data format
> refactor: add option for response data format

- src/spaceone/inventory/service/collector_service.py
> fix: fix indent

- src/spaceone/inventory/plugin/collector/lib/utils.py
- src/spaceone/inventory/service/cloud_service_service.py
- src/spaceone/inventory/service/cloud_service_type_service.py
- src/spaceone/inventory/service/collector_service.py
> Fix Type Bug

- src/spaceone/inventory/manager/collecting_manager.py
- remove update field if `query_options` are same
> refactor: remove update field if query_options are same

- src/spaceone/inventory/plugin/collector/conf/global_conf.py
> feat: add cache settings

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
> refactor: refactor metadata generator

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
> fix: fix wrong default parameter

- src/spaceone/inventory/service/metric_data_service.py
> fix: apply parameter validation

- src/spaceone/inventory/manager/collecting_manager.py
- add concurrency metadata for collector
> refactor: add concurrency metadata for collector

- src/spaceone/inventory/manager/collecting_manager.py
- add sleep time when retrying job task
> refactor: add sleep time when retrying job task

- src/spaceone/inventory/manager/job_manager.py
- fix metric filter bug when collecting resources
> fix: fix metric filter bug when collecting resources

- src/spaceone/inventory/plugin/collector/lib/utils.py
Add generate_metadata option of make_cloud_service_type
> Add generate_metadata option of make_cloud_service_type

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/model/dynamic_view.py
- Added `table.options.default_filters` to metadata_generator.py
- Added 'Filter' class that has 'key', 'value', and 'operator'
> Added `table.options.default_filters` to metadata_generator.py

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/model/dynamic_view.py
- Removed an unnecessary line indent
- Fixed an attribute name for a deprecated class `Options`
> Made minor style changes in `metadata_generator.py` and `dynamic_view.py`

- src/spaceone/inventory/plugin/collector/model/dynamic_view.py
- Removed a deprecated class `Options` in 'dynamic_view.py'
> Removed a deprecated class `Options` in 'dynamic_view.py'

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- Simplified(fixed) return type of _generate_filters() for python version dependency
> Simplified return type of _generate_filters() for python version dependency

- src/spaceone/inventory/plugin/collector/lib/metadata_generator.py
- src/spaceone/inventory/plugin/collector/model/field.py
> Add list, size field options

- src/spaceone/inventory/service/collector_service.py
- fix collector secret filter with workspace_id
> Fix collector secret filter with workspace_id

- src/spaceone/inventory/manager/collector_manager.py
- src/spaceone/inventory/service/collector_service.py
- modify logic for getting collector_workspace_id
> Modify logic for getting collector_workspace_id

- src/spaceone/inventory/plugin/collector/lib/metadata.py
- src/spaceone/inventory/plugin/collector/lib/utils.py
* When creating cloud_service_type in plugin, change to create it with dict type metadata without metadata_path
> Add metadata parameter when using plugin method

- src/spaceone/inventory/service/cloud_service_service.py
- src/spaceone/inventory/service/metric_data_service.py
- remove pagination from stat and analyze queries
> refactor: remove pagination from stat and analyze queries

- src/spaceone/inventory/managed_resource/metric/iam_service_account_count.yaml
- src/spaceone/inventory/managed_resource/namespace/iam_summary.yaml
- src/spaceone/inventory/manager/identity_manager.py
- src/spaceone/inventory/manager/metric_manager.py
feat: add service account metric.
> Add service account metric.

- src/spaceone/inventory/manager/metric_manager.py
fix: add full path for import identity manager.
> Add full path for import identity manager.

- src/spaceone/inventory/conf/global_conf.py
- src/spaceone/inventory/connector/file_upload_connector.py
- src/spaceone/inventory/manager/export_manager/__init__.py
- src/spaceone/inventory/manager/file_manager.py
- src/spaceone/inventory/manager/namespace_manager.py
> Add new files upload connector

- src/spaceone/inventory/conf/global_conf.py
- src/spaceone/inventory/connector/file_upload_connector.py
- src/spaceone/inventory/manager/export_manager/__init__.py
- src/spaceone/inventory/manager/file_manager.py
> Remove unused code

- src/spaceone/inventory/manager/export_manager/__init__.py
- src/spaceone/inventory/manager/export_manager/email_manager.py
> Recover download url format

- src/spaceone/inventory/plugin/collector/conf/global_conf.py
- change default max workers for inventory plugins
> refactor: change default max workers for inventory plugins

- src/spaceone/inventory/plugin/collector/conf/global_conf.py
> refactor: remove worker settings

- src/spaceone/inventory/manager/metric_data_manager.py
- src/spaceone/inventory/manager/metric_manager.py
- src/spaceone/inventory/service/metric_data_service.py
- add project_group filter to metric data query
> feat: add project_group filter to metric data query
